// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hackersvc.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	hackersvc.proto

It has these top-level messages:
	PingRequest
	PingReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The ping request contains no.
type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The ping response should just contain "pong" in `p`
type PingReply struct {
	P   string `protobuf:"bytes,1,opt,name=p" json:"p,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingReply) GetP() string {
	if m != nil {
		return m.P
	}
	return ""
}

func (m *PingReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "pb.PingRequest")
	proto.RegisterType((*PingReply)(nil), "pb.PingReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hacker service

type HackerClient interface {
	// Returns "Pong"
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type hackerClient struct {
	cc *grpc.ClientConn
}

func NewHackerClient(cc *grpc.ClientConn) HackerClient {
	return &hackerClient{cc}
}

func (c *hackerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/pb.Hacker/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hacker service

type HackerServer interface {
	// Returns "Pong"
	Ping(context.Context, *PingRequest) (*PingReply, error)
}

func RegisterHackerServer(s *grpc.Server, srv HackerServer) {
	s.RegisterService(&_Hacker_serviceDesc, srv)
}

func _Hacker_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HackerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Hacker/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HackerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hacker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Hacker",
	HandlerType: (*HackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Hacker_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hackersvc.proto",
}

func init() { proto.RegisterFile("hackersvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0x2a, 0x2e, 0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0xe2, 0xe5, 0xe2, 0x0e, 0xc8, 0xcc, 0x4b, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0xd2,
	0xe6, 0xe2, 0x84, 0x70, 0x0b, 0x72, 0x2a, 0x85, 0x78, 0xb8, 0x18, 0x0b, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x18, 0x0b, 0x84, 0x04, 0xb8, 0x98, 0x53, 0x8b, 0x8a, 0x24, 0x98, 0xc0, 0x7c,
	0x10, 0xd3, 0xc8, 0x88, 0x8b, 0xcd, 0x03, 0x6c, 0xa4, 0x90, 0x06, 0x17, 0x0b, 0x48, 0x9b, 0x10,
	0xbf, 0x5e, 0x41, 0x92, 0x1e, 0x92, 0x79, 0x52, 0xbc, 0x08, 0x81, 0x82, 0x9c, 0x4a, 0x25, 0x86,
	0x24, 0x36, 0xb0, 0xd5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x14, 0xad, 0x39, 0x8d,
	0x00, 0x00, 0x00,
}
